# espanso match file
# Official docs: https://espanso.org/docs/

matches:
  # Simple text replacement
  - trigger: ":espanso"
    replace: "Hi there!"

# ------------------------------------------------------------------------------------
# Functional Snippets
# ------------------------------------------------------------------------------------

# Date: Generates a date string in the format YYYY-MM-DD
  - trigger: ";date"
    replace: "{{mydate}}"
    vars:
      - name: "mydate"
        type: "date"
        params:
          format: "%Y-%m-%d"

# Time: Generates a time string in the format HH:MM:SS
  - trigger: ";time"
    replace: "{{mytime}}"
    vars:
      - name: "mytime"
        type: "date"
        params:
          format: "%H:%M:%S"

# Shell: Executes a shell command and replaces the trigger with the output
  - trigger: ":shell"
    replace: "{{output}}"
    vars:
      - name: output
        type: shell
        params:
          cmd: "echo 'Hello from your shell'"

# ------------------------------------------------------------------------------------
# Ticket Responses
# ------------------------------------------------------------------------------------

# Triage: Generates a triage note with incident/service request details
  - trigger: ":triage"
    replace: |
      Phone / Walk Up / Other
      -----------------------------------
      Incident / Service Request Description
       - 

      First Reported
       - 
       
      Users Affected
       - 

# Response: Generates a basic respons etemplate for IT support
  - trigger: ":response"
    replace: |
      Thank you for reaching out to the IT support team. I wanted to confirm that we've received your request and I will get this assigned to the relevant team to further assist.

      We will keep you updated on our progress, and we'll let you know as soon as we have more information. If you have any additional details or if anything changes, please feel free to reply to this message.
      Your patience is greatly appreciated.

      Best regards,
      Luigi

# KR: Generates a "Kind Regards" response template
  - trigger: ":kr"
    replace: |
      Kind regards,
      Luigi
  
# All Net: Generates a response template for all network-related issues
  - trigger: ":all-net"
    replace: |
      Hi Team,

      I hope you are well.
      I will raise this with the networking team now.
      If there is anything else that you need to add to this ticket, please feel free to reply to this email.

      Kind regards,
      Luigi

# ------------------------------------------------------------------------------------
# Ticket Notes
# ------------------------------------------------------------------------------------

# Ticket Note: Generates a detailed ticket note with user and device information
  - trigger: ";ticketnote"
    replace: |
      🎫 Ticket ID:
      🗓️ Date: {{mydate}}
      ---------------------------------------
      👤 User Details:
      - Name: 
      - Email Address: 
      - Phone Number: 
      - Location: 
      - Username: 
      ---------------------------------------
      🖥️ Device Information:
      - Device Type: 
      - Hostname: 
      - Operating System: 
      - Asset Tag/Serial Number: 
      - IP Address: 
      - MAC Address: 
      - Description: 
      ---------------------------------------
      ⚠️ Issue Summary:
      - Reported Problem: 
      - Error Messages (if any): 
      - Frequency: 
      - Recent Changes: 
      ---------------------------------------
      🔧 Troubleshooting Steps Taken:
      1. [Step 1]
      2. [Step 2]
      3. [Step 3]
      - Outcome: [Resolved / Escalated / Pending Further Action]
      ---------------------------------------
      🛟 Next Steps:
      - Assigned to: 
      - Follow-up required: [Yes/No]
      - ETA for resolution: [Insert timeframe]
      - Actions: [Insert actions to be taken]
      ---------------------------------------
      ℹ️ Notes & Additional Information:
      - Related Tickets:
      - Additional Comments:
       - >> 
      ---------------------------------------
    vars:
      - name: "mydate"
        type: "date"
        params:
          format: "%Y-%m-%d"

# Quote: Generates a quote template with date and source information
  - trigger: ";quote"
    replace: |
      -----------------------------------------------------
      💬 "$|$"
      -----------------------------------------------------
      Source: [Person, Document, or Ticket ID]
      Date: {{mydate}}
      Additional Notes: [Context or explanation related to the quote]
      -----------------------------------------------------
    vars:
      - name: "mydate"
        type: "date"
        params:
          format: "%Y-%m-%d"

# Follow-Up: Generates a follow-up note with actions and results
  - trigger: ";followup"
    replace: |
      🛟 Follow-Up Scheduled: 
      --------------------------------
      🔧 Actions To Be Taken:
      1. [Step 1: Checked system status]
      2. [Step 2: Communicated with user]
      3. [Step 3: Applied fixes or escalations]
      --------------------------------
      ✅ Follow-Up Completed:
      - Outcome: [Resolved / Further investigation required]
      --------------------------------
      📃 Results:
      - Assigned to: [Self / Escalated]
      - Follow Up Date: [YYYY-MM-DD]
      - Further follow-up required: [Yes/No]
      - Next Steps: [N/A / Further investigation / Escalation]
      --------------------------------
      ℹ️ Additional Notes:
      - [Any new observations, feedback from the user, or related logs]
      -----------------------------------
    vars:
      - name: "mydate"
        type: "date"
        params:
          format: "%Y-%m-%d"
  
# Closing Ticket: Generates a closing ticket note with user and device information
  - trigger: ";closingticket"
    replace: |
      Good morning / afternoon $|$,

      I hope this message finds you well.
      I wanted to follow up on the ticket you raised with us regarding [insert issue description]. We’ve made three attempts to reach out regarding your reported issue [Ticket ID], but unfortunately, we haven’t received a response.
      As per our support protocol, we’ll be closing this ticket now to ensure our resources are allocated efficiently. Should you still require assistance, please respond to this email which will automatically open the ticket.

      Thank you for your understanding, and we’re here if you need further help in the future.

      Best regards,  
      Luigi

# ------------------------------------------------------------------------------------
# Emoji Replacements
# ------------------------------------------------------------------------------------

# Check: Generates a checkmark symbol
  - trigger: ";check"
    replace: ✅

# Cross: Generates a cross mark symbol
  - trigger: ";cross"
    replace: ❌

# Star: Generates a star symbol
  - trigger: ";star"
    replace: ⭐

# ------------------------------------------------------------------------------------
# Depreciated
# ------------------------------------------------------------------------------------

# Depreciated - INote: Generates a detailed ticket note with user and device information
  - trigger: ":inote"
    replace: |
      User Details
       - Name: 
       - Username: 
       - Email Address: 
       - Location: 
       - Phone Number: 
      -----------------------------------
      Device Details
       - Hostname: 
       - IP Address: 
       - MAC Address: 
       - OS: 
       - Description: 
      -----------------------------------
      Ticket Details
       - Priority: 
       - Type: 
       - Category: 
      -----------------------------------
      References
       - 

      Notes
       - 

      Resolution
       - [ To Be Confirmed ]
  
# Depreciated - Note: Generates an update ticket note with user and device information
  - trigger: ":note"
    replace: |
      Update: 
      -----------------------------------
      Notes 
       - 

      Next Steps / Resolution
       - 

# Depreciated - Follow Up: Generates a follow-up note with date, time, and reason
  - trigger: ":follow"
    replace: |
      Follow Up
      -----------------------------------
      Date: 
      Time: 
      Reason: 
      Actions: 
      -----------------------------------